apiVersion: skaffold/v4beta10
kind: Config

# This Skaffold configuration expects to find a skaffold.env file in the current directory.
# It should contain the following environment variables:
# - SKAFFOLD_DEFAULT_REPO: The default repository to use for images
# - rpm_repo: The URL of the RPM repository for MARS/GribJump/FDB images
# - mars_config_repo: The URL of the MARS configuration repository
# - mars_config_branch: The branch of the MARS configuration repository to use
# - ssh_pub_key: The public SSH key to use for cloning the MARS and MARS configuration repositories
# - ssh_prv_key: The private SSH key to use for cloning the MARS and MARS configuration repositories


build:
  local:
    useBuildkit: True
    concurrency: 1
  tagPolicy:
    customTemplate:
      template: "{{.PREFIX}}{{.GIT_TAG}}"
      components:
      - name: PREFIX
        envTemplate:
          template: '{{default "" .PREFIX}}'
      - name: GIT_TAG
        gitCommit:
          ignoreChanges: true
  platforms:
    - linux/amd64
    # - linux/arm64
  artifacts:
  
  # Polytope common   
  - image: "polytope-common"
    docker:
      target: polytope-common
      buildArgs:
        developer_mode: '{{ default "false" .developer_mode }}'

  # Worker with all clients (FDB, GribJump, MARS C, MARS CPP)
  - image: "worker"
    docker:
      target: worker
      buildArgs:
        rpm_repo: '{{ .rpm_repo }}'
        mars_config_repo: '{{ .mars_config_repo }}'
        mars_config_branch: '{{ .mars_config_branch }}'
        developer_mode: '{{ default "false" .developer_mode }}'
        # mars_client_c_version: 6.33.20.2
        gribjump_version: '{{ default "0.10.0" .gribjump_version }}'
        mars_client_cpp_version: 7.1.6.3
        # ecbuild_version: 3.8.2
        # eccodes_version: 2.33.1
        # eckit_version: 1.28.0
        # pyfdb_version: 0.1.0
        # fdb_version: 5.13.2
        mars_base_c: '{{ if eq .mars_base_c "1" }}mars-base-c{{ else }}blank-base{{ end }}'
        mars_base_cpp: '{{ if eq .mars_base_cpp "1" }}mars-base-cpp{{ else }}blank-base{{ end }}'
        fdb_base: '{{ if eq .fdb_base "1" }}fdb-base{{ else }}blank-base{{ end }}'
        gribjump_base: '{{ if eq .gribjump_base "1" }}gribjump-base{{ else }}blank-base{{ end }}'
      # cliFlags: 
      #   - --no-cache # for debug purposes

deploy:
  helm:
    releases:
      - name: polytope-dev
        chartPath: ../polytope-chart
        setValueTemplates:
          # deployment.registry: '{{.IMAGE_REGISTRY_worker}}'
          deployment.fqn_images.polytope_common: '{{.IMAGE_FULLY_QUALIFIED_polytope_common}}'
          deployment.fqn_images.worker: '{{.IMAGE_FULLY_QUALIFIED_worker}}'
        valuesFiles:
          - ../polytope-chart/values.yaml
        wait: false
        overrides:
          deployment:
            worker:
              replicas: 1
            frontend:
              replicas: 1

profiles:
  - name: lumi-dev
    deploy:
      helm:
        releases:
          - name: polytope-dev
            chartPath: ../polytope-chart
            valuesFiles:
              - ../polytope-chart/values.yaml
              - ../polytope-config/common.yaml
              - ../polytope-config/location/lumi.yaml
              - ../polytope-config/env/dev.yaml