apiVersion: skaffold/v4beta10
kind: Config

build:
  local:
    useBuildkit: True
    concurrency: 1
  tagPolicy:
    customTemplate:
      template: "{{.PREFIX}}{{.GIT_TAG}}"
      components:
      - name: PREFIX
        envTemplate:
          template: '{{default "" .PREFIX}}'
      - name: GIT_TAG
        gitCommit:
          ignoreChanges: false
  platforms:
    - linux/amd64
  artifacts:
  - image: "mars-base-c"
    docker:
      dockerfile: Dockerfile.mars-client-source
      target: mars-base-c
      cliFlags:
        - --secret=id=github_token,env=GITHUB_TOKEN
      buildArgs:
        ecbuild_version: '{{ default "3.14.0" .ecbuild_version }}'
        mars_client_c_bundle_ref: '{{ default "develop" .mars_client_c_bundle_ref }}'
  - image: "mars-base-cpp"
    docker:
      dockerfile: Dockerfile.mars-client-source
      target: mars-base-cpp
      cliFlags:
        - --secret=id=github_token,env=GITHUB_TOKEN
      buildArgs:
        ecbuild_version: '{{ default "3.14.0" .ecbuild_version }}'
        mars_client_cpp_bundle_ref: '{{ default "develop-cpp" .mars_client_cpp_bundle_ref }}'
