apiVersion: skaffold/v4beta10
kind: Config

# This Skaffold configuration expects to find a skaffold.env file in the current directory.
# It should contain the following environment variables:
# - SKAFFOLD_DEFAULT_REPO: The default repository to use for images
# - rpm_repo: The URL of the RPM repository for MARS/GribJump/FDB images
# - mars_config_repo: The URL of the MARS configuration repository
# - mars_config_branch: The branch of the MARS configuration repository to use
# - ssh_pub_key: The public SSH key to use for cloning the MARS and MARS configuration repositories
# - ssh_prv_key: The private SSH key to use for cloning the MARS and MARS configuration repositories


build:
  local:
    useBuildkit: True
    concurrency: 1
  tagPolicy:
    customTemplate:
      template: "{{.PREFIX}}{{.GIT_TAG}}"
      components:
      - name: PREFIX
        envTemplate:
          template: '{{default "" .PREFIX}}'
      - name: GIT_TAG
        gitCommit:
          ignoreChanges: true
  platforms:
    - linux/amd64
    # - linux/arm64
  artifacts:
  
  # Polytope common   
  - image: "polytope-common"
    docker:
      target: polytope-common
      buildArgs:
        developer_mode: '{{ default "false" .developer_mode }}'

  # Worker with source-built GribJump and optional MARS clients
  - image: "worker"
    docker:
      target: worker
      buildArgs:
        rpm_repo: '{{ .rpm_repo }}'
        mars_config_repo: '{{ .mars_config_repo }}'
        mars_config_branch: '{{ .mars_config_branch }}'
        developer_mode: '{{ default "false" .developer_mode }}'
        polytope_python_git: '{{ default "https://github.com/ecmwf/polytope.git" .polytope_python_git }}'
        polytope_python_ref: '{{ default "feat/sub_hourly_mixed_steps" .polytope_python_ref }}'
        mars_client_c_version: '{{ default "6.33.20.2" .mars_client_c_version }}'
        mars_client_cpp_version: '{{ default "7.1.9.1" .mars_client_cpp_version }}'
        ecbuild_version: '{{ default "3.14.0" .ecbuild_version }}'
        libaec_version: '{{ default "v1.1.4" .libaec_version }}'
        eckit_version: '{{ default "1.33.2" .eckit_version }}'
        eccodes_version: '{{ default "2.46.0" .eccodes_version }}'
        metkit_version: '{{ default "1.18.1" .metkit_version }}'
        fdb_version: '{{ default "5.21.3" .fdb_version }}'
        gribjump_version: '{{ default "0.12.0" .gribjump_version }}'
        mars_base_c: '{{ if eq .mars_base_c "1" }}mars-base-c{{ else }}blank-base{{ end }}'
        mars_base_cpp: '{{ if eq .mars_base_cpp "1" }}mars-base-cpp{{ else }}blank-base{{ end }}'
        gribjump_source_base: '{{ if eq .gribjump_source_base "1" }}source-gribjump-worker-python{{ else }}blank-base{{ end }}'
      # cliFlags: 
      #   - --no-cache # for debug purposes
